# TODO: Add plugin config
# TODO: Add Local SSL + NGINX

version: "3.5"
networks:
  http_net:
  db_net:
  es_net:

volumes:
  cms-shared:
  dbdata:
  esdata:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - cluster.name=elastic-cluster
      - discovery.type=single-node
      - data
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xmx1G"
    ports:
    - 9200:9200
    - 9600:9600
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - es_net
        
  dotcms:
    image: dotcms/dotcms:5.3.8.4lts
    ports:
      - 8080:8080
      - 8000:8000
      - 9010:9010
    networks:
      - db_net
      - es_net
    environment:
      - CMS_JAVA_OPTS=-XX:+PrintFlagsFinal -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.host=0.0.0.0 -Djava.rmi.server.hostname=0.0.0.0
      - PROVIDER_DB_DNSNAME=db
      - PROVIDER_DB_DRIVER=POSTGRES
      - PROVIDER_DB_DBNAME=dotcms
      - PROVIDER_DB_USERNAME=dotcmsdbuser
      - PROVIDER_DB_PASSWORD=password
      - PROVIDER_ELASTICSEARCH_ENDPOINTS=http://elasticsearch:9200
      - ES_ADMIN_PASSWORD=admin
    depends_on:
      - db
      - elasticsearch
    volumes:
      - ./dotCMS/license/dotCMSLicensePack1581442753219.zip:/data/shared/assets/license.zip
      - ./dotCMS/empty-starter-site:/plugins/static/com.willowtree.tardigrade.plugins.emptystartersite
      - ./dotCMS/osgi-extra.conf:/data/local/felix/osgi-extra.conf
  db:
    image: bitnami/postgresql:9.6
    environment:
      - POSTGRESQL_USERNAME=dotcmsdbuser
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=dotcms
    networks:
      - db_net
  db_admin:
    image: dpage/pgadmin4:latest
    networks:
      - db_net
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./dotCMS/db-servers.json:/pgadmin4/servers.json
    ports:
      - 9090:80
#  search:
#    image: dotcms/elasticsearch:6.1.3-os
#    ports:
#      - 9200:9200
#    environment:
#      - PROVIDER_ELASTICSEARCH_HEAP_SIZE=1500m
#      - PROVIDER_ELASTICSEARCH_DNSNAMES=search
#      - PROVIDER_ELASTICSEARCH_SVC_DELAY_MIN=1
#      - PROVIDER_ELASTICSEARCH_SVC_DELAY_STEP=1
#      - PROVIDER_ELASTICSEARCH_SVC_DELAY_MAX=2